### ISSUE TITLE
Block number in csv file

### ISSUE THREAD

**Issue by kargakis** [btcsuite/btcsim#35]
Currently the block number specified in a csv file [first value of the two] plays no part other than being the first value of a record. There are two options: either leave it as is or have it actively participate in a simulation. In the first case it's much simpler and probably better for running btcsim but it currently accepts csv files that we literately don't care about the one of the two fields ie. half the csv file. In the second case, we will have to add some restrictions about compliance of the block numbers in the csv file (comparison with ```matureBlock```, ```maxBlocks```, every block number must be different from the rest, etc.) which won't be a gain for btcsim other than accepting a well-defined csv only.

**Comment by tuxcanfly** [comment]
This can be marked completed and closed as we are now accepting block height as the first CSV column.
